### ISSUE TITLE
credhist try_credential

### ISSUE THREAD

**Issue by kabutor** [tijldeneut/DPAPIck3#3]
Probably I'm doing something wrong but if I try 
```
mkp = masterkey.MasterKeyPool()
mkp.loadDirectory(masterkey_location)
mkp.addCredhistFile(sid,os.path.join(add_path,"Protect", "CREDHIST"))
#print(mkp.creds[sid])
mkp.try_credential(sid,password)
```

```
Traceback (most recent call last):
  File "/root/temp/master.py", line 26, in <module>
    mkp.try_credential(sid,password)
  File "/usr/local/lib/python3.10/dist-packages/dpapick3/masterkey.py", line 508, in try_credential
    self.creds[userSID].decryptWithPassword(password)                                                                                                                                       
  File "/usr/local/lib/python3.10/dist-packages/dpapick3/credhist.py", line 244, in decryptWithPassword
    return self.decryptWithHash(hashlib.sha1(pwd.encode("UTF-16LE")).digest())
  File "/usr/local/lib/python3.10/dist-packages/dpapick3/credhist.py", line 235, in decryptWithHash
    entry.decryptWithHash(curhash)
  File "/usr/local/lib/python3.10/dist-packages/dpapick3/credhist.py", line 148, in decryptWithHash
    self.decryptWithKey(crypto.derivePwdHash(pwdhash, str(self.userSID)))
  File "/usr/local/lib/python3.10/dist-packages/dpapick3/crypto.py", line 312, in derivePwdHash
    return hmac.new(pwdhash, (userSID + "\0").encode("UTF-16LE"), digestmod=getDigestmod(digest)).digest()
  File "/usr/lib/python3.10/hmac.py", line 184, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.10/hmac.py", line 53, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'NoneType'
```

I can see that the credhist file is loaded if I remove the # on the print(mkp.creds[sid]) line, but I'm stuck on this

dpapick3                       0.4.0

**Comment by tijldeneut** [comment]
Hi, thank you for the issue.
Does parsing and/or decrypting the CREDHIST file itself work?
CFR: https://github.com/tijldeneut/dpapilab-ng/blob/main/credhistdec.py 

Maybe something has changed in Windows that requires a DPAPICK3 update.

**Comment by kabutor** [comment]
I'm sorry, I don't have the file any more, I needed it for decrypting a certificate and I just did it other way.

It was a weird credhist file, it has 11 entries, for what I seen is more than the average ones I usually see around, I open this issue but I never tried with more than one credhist file, so it can be an issue with that file, maybe was corrupt.
Let me close the issue, I'll check it next time and if I have a problem I'll find a way to attach the file
Sorry for your time

**Comment by kabutor** [comment]
I'm back less than 2 years later, been doing some tests and there is a problem in dpapick3/credhist.py

CREDHIST keeps encrypting the password using the old password, but if something fails, for example a password change is forced by an admin credhist.py assings a null value to curhash and the program crashes as in the first post.
A simple change is to only assign curhash if not None the decryption

```
    def decryptWithHash(self, h):
        """Try to decrypt each entry with the given hash"""
        if self.valid:
            return
        curhash = h
        for entry in self.entries_list:
            entry.decryptWithHash(curhash)
            if entry.pwdhash != None:
                curhash = entry.pwdhash
```
I'm trying to attach a CREDHIST file so you can test it, I did 4 password changes using test1, test2, test3 and test4 as the password, but test3 was forced (so only 3 passwords are keep on the CREDHIST)

If you try to decrypt it (using diana-credhistdec.py for example) it will crash, with the fix, if you use test4 or test1 as the password it will decrypt 1 key, if you use test2, it will decrypt two

[CREDHIST.txt](https://github.com/user-attachments/files/20843978/CREDHIST.txt)

**Comment by kabutor** [comment]
Maybe this is not the best place to post this, but I will find it very useful if you could dump the encrypted hashes from CREDHIST to try to crack with hashcat. Don't know if that can already be done or some extra work is needed
